#Ce programme permet de créer un questionnaire interactif qui collecte des informations personnelles et génère un profil personnalisé
print()
print()
print("===============================================================================")
print("VOTRE PROFIL PERSONNEL")
print("===============================================================================")
print()
nom=str(input("Nom : "))
age=int(input("Age : "))
ville=str(input("Ville : "))
print()
print("PREFERENCES")
couleur=str(input("Couleur : "))
plat=str(input("Plat : "))
sport=str(input("Sport : "))
music=str(input("Musique : "))
print()
print("PROJETS ET AMBITIONS")
metier=str(input("Métier souhaité : "))
objectif=str(input("Objectif 2025 : "))
print()
print("LOISIRS")
loisir=str(input("Lecture : "))
occupation=str(input("Weekend : "))
print()
print(f"{nom}, Votre profil est maintenant crée !\nVous êtes une personne de {age} ans passionnée par {metier}")