print("nous voulons calculer les economies personneles:")
nom = str(input("veuiller entrer le nom de l utilisateur:"))
revenu = float(input("veuiller entrer le revenu mensuel:"))
depense = float(input("veuiller entrer les dépenses:"))
montant_economiser = revenu - depense
taux_epargne = ((montant_economiser/revenu) * 100)
print("                                                                      ")
print("                                                                      ")
print("===BILAN MENSUEL===")
print("nom-revenu:",revenu)
print("depenses:",depense)
print("economies:",montant_economiser)
print("Taux d'epargne :",taux_epargne)
print("                                                                   ")
print("                                                                             " )
print("                                                                      ")
print("                                                                           ")
print("Bienvenue dans la création de profil personnel de vos rêve")
nom = str(input("Quel est votre nom complet?"))
age = int(input("Quel âge avez-vous?"))
ville = str(input("Dans quelle ville habitez-vous?"))
couleur = str(input("Quelle est votre couleur préférée?"))
plat = str(input("Quel est votre plat favori?"))
sport = str(input("Quel sport pratiquez-vous?"))
metier = str(input("Quel métier voulez-vous faire?"))
objectif = str(input("Quel est votre objectif cette année?"))
livre = str(input("Quel est votre livre préféré?"))
muisique = str(input("Quel type de muisique aimez-vous?"))
week = str(input("Que faites-vous le weekend?"))
print("                                                                                       ")
print("                                                                                        ")
print("                                                                                        ")
print("===========================================================")
print("                VOTRE PROFIL PERSONNEL                     ")
print("===========================================================")
print("Nom:",nom)
print("Age:",age)
print("Ville:",ville)
print("                                                               ")
print("                                                                       ")
print("PREFERENCES")
print("Couleur:",couleur)
print("Plat:",plat)
print("Sport:",sport)
print("Muisique:",muisique)
print("                                                           ")
print("                                                             ")
print("PROJETS ET AMBITIONS")
print("Metier:",metier)
print("Objectif:",objectif)
print("                                                            ")
print("                                                              ")
print("LOISIRS")
print("Lecture:",livre)
print("Weekend:",week)
print("                                               ")
print("                                                ")
print(f"{nom}, votre profil est maintenant créé !\nVous êtes une personne de {age} passionnée par {metier}.")



