print("nous voulons calculer les economies personneles:")
nom = str(input("veuiller entrer le nom de l utilisateur:"))
revenu = float(input("veuiller entrer le revenu mensuel:"))
depense = float(input("veuiller entrer les dépenses:"))
montant_economiser = revenu - depense
taux_epargne = ((montant_economiser/revenu) * 100)
print("                                                                      ")
print("                                                                      ")
print("===BILAN MENSUEL===")
print("nom-revenu:",revenu)
print("depenses:",depense)
print("economies:",montant_economiser)
print("Taux d'epargne :",taux_epargne)
print("                                                                   ")
print("                                                                             " )
print("                                                                      ")
print("                                                                           ")